99 display metadata in entities app
N5GEH/n5geh.tools.entirety pull request #118
Opened 2023-07-07 09:44 UTC by sbanoeon

2023-08-01 15:51 UTC, djs0109 commented
LGTM! Could you provide a button to beautify the metadata?

2023-08-02 06:58 UTC, sbanoeon commented
@djs0109 Currently, the json beautifies when user focuses on the metadata field. Do you think there should be a separate button for it?

2023-08-02 07:28 UTC, djs0109 commented
@sbanoeon I overlooked that. I think this feature is pretty cool!

2023-08-02 07:47 UTC, djs0109 requested changes

2023-08-02 07:47 UTC, djs0109 commented on app/Entirety/entities/views.py
> +                    attr.metadata = json.load(self.request.POST.get(keys[3]))
Should it be json.loads() here?

2023-08-02 07:47 UTC, djs0109 commented on app/Entirety/entities/views.py
> +                attr.metadata = json.loads(self.request.POST.get(new_keys[3]))
Please add error handling for Validation Error

2023-08-02 07:47 UTC, djs0109 commented on app/Entirety/entities/views.py
> +                    attr.metadata = json.load(self.request.POST.get(keys[3]))
Would that increase the stability, when the users delete the default value of meta data? The same for update.
```python
attr.metadata = json.load(self.request.POST.get(keys[3])) \
     if self.request.POST.get(keys[3]) else {}
```

2023-08-14 15:03 UTC, djs0109 approved these changes

2023-08-15 06:34 UTC, merged